### ISSUE TITLE
how to get for different phases

### ISSUE THREAD

**Issue by sjlukacs** [chmarti1/PYroMat#12]
forgive me, i'm unclear how to get the values for the enthalpy and entropy of liquid states, for instance, from the ig table.  to solve problems like, calculate the enthalpy and entropy for the following reactions:

H2O(l) -> H2O(g)
or
2HCl(g) + Pb(s) -> PbCl2(s) + H2(g)

thank you in advance, lucas

**Comment by chmarti1** [comment]
PYroMat currently includes two collections: ig (ideal gas) and mp (multi-phase).  The multi-phase collection includes water, so

>>> import pyromat as pm
>>> H2O = pm.get('mp.H2O')
>>> hL,hV = H2O.hs(p=1.01325)
>>> sL,sV = H2O.ss(p=1.01325)

This gives you the liquid and vapor enthalpies and entropies for the phase transition at 1 standard atmosphere (1.01325bar).  The enthalpy of vaporization would be (hV - hL).

Type
>>> help(H2O)

to get more information.

All of the ig (ideal gas) collection data in PYroMat are for the gas phase only, so you'll only be able to get the vapor side for the lead-acid reaction you list there.  You would have to model the solid enthalpy yourself.  It depends on what you're doing, but you may be able to use a simple constant-specific heat model, so entropy and enthalpy calculations could be quite simple.  At the moment, PYroMat does not have data on solid substances; only vapor and a little liquid.

              T
h - h0 = int  c dT  =  c (T-T0)      (assume const. c)
              T0

              T
s - s0 = int  c/T  dT = c ln (T/T0)      (assume incompressible)
              T0

This breaks if the temperature ranges are very wide, because solids don't really have constant specific heats; especially when T is very low.

The simplest approach is to just use an enthalpy/entropy of reaction and assume the phases are at the same temperature.  Again, it depends on what you're doing as to whether or not that's enough.

Hope that helps!


Christopher R. Martin Ph.D.

Assistant Professor of Mechanical Engineering

Penn State University - Altoona College

(+1 814) 949-5227

https://sites.psu.edu/cmartin


________________________________
