### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by Matthew-Mullin** [chmarti1/PYroMat#17]
Just wanted to say: Pretty cool library. I'm coming from EES and need something that can handle matrices/arrays better, which is why I'm using Python, but I think this library could benefit from:

.v() method for getting specific volume. I know you can just do 1/air.d(), but I would think this would be fairly simple to add.

**Comment by chmarti1** [comment]
I agonized about this question for some time when I first designed the PYroMat interface.  The reasons to add specific volume are obvious, and you're right, quite a few users would probably like having that option.  The question is a good one, so I'll try to answer it here meaningfully.  This is hardly the last word on the matter.  Especially if large numbers of users agree, I may still add specific volume one day.

I decided to deal in density on the back end because that's how all of the properties are most conveniently calculated.  For ideal gases, it makes little difference, but for multi-phase substances, density is really the way to go.

In terms of the interface, there are two ways to implement your suggestion: (1) I could just make a new property called .v(), or (2) I could make specific heat a new primary property, adding it as a valid argument to all properties.  The first option would be a one-line function v = 1/d.  That's so easy, users can do that themselves if they want.  Now, let's deal with option 2...

If I included specific volume as a primary property, users would be able to specify a state with T, p, d, v, and x.  The number of possible combinations is N*(N-1)/2, so I need to case out 10 different scenarios; many of which will not be valid, and most of which will not be useful.  Right now, I only need to deal with 6.  This is not a terribly difficult problem, but it does add complexity to the _argparse() methods.

So far, it hasn't been worth it to go that route.  Still, your suggesting is banging around in the back of my head.  Let's see if folks want this feature, and maybe I'll fold it into the plans for the next major release.

**Comment by jranalli** [comment]
Chris,

For what it's worth, my personal opinion is that the read-only property version of v = return 1/self.d() would be useful to have baked in. I agree that it's sufficiently trivial to do yourself but that requires every user to either creating their own wrapper around the existing class library or make an auxiliary function that doesn't otherwise look like the existing library. For that matter, you could actually create other derived props like gibbs, helmholz, etc. if you wanted to establish more of the ideology that some things are just read-only. The definitions of these are unambiguous, easy to implement and might be helpful to users.

I 100% agree that it's reasonable to avoid making v a primary property at present.

Best,
Joe
________________________________

**Comment by chmarti1** [comment]
Now that I spend some time thinking about it, there are some ways to reduce the complexity burden on _argparse().  This may be doable for version 2.2.0.

**Comment by Matthew-Mullin** [comment]
Thank you for the detailed response. Ultimately, I think option 2 might be the best for consistency. One workaround might be to raise an error if both v & d are passed and to convert v to d early in the _argparse() function, maybe above the "if d is not None:" line.

**Comment by chmarti1** [comment]
I agree.  What you propose deals with the problem nicely, and it really doesn't add much complexity.  I'll keep this in mind for the next major release.  In the meantime, I'll leave this issue open for people to add comments if they want.

**Comment by chmarti1** [comment]
Update: The next release will include specific volume as a recognized property.  I've rewritten _argparse() to make a more flexible property specification interface, and v is a part of it.  Thanks for your input!

**Comment by chmarti1** [comment]
After quite a bit of testing, and quite a bit of code, version 2.2.0 is finally almost ready for release.  This feature suggestion is part of the new back-end.  Thanks for your input!
