### ISSUE TITLE
Bugs in mp1.d_s

### ISSUE THREAD

**Issue by jranalli** [chmarti1/PYroMat#19]
Some weird behaviors in mp1.d_s

First, when seeking values above the critical point:
```
import pyromat as pm

pm.config['unit_pressure'] = 'MPa'
F = pm.get('mp.H2O')

F.d_s(T=1209.35, s=5.5)  # Should yield around 580.555 kg/m3
# Raises PMParamError: _HYBRID1: At least one max/min value does not bracket a solution!
```

When seeking values below the critical point but not requesting the quality be returned:
```
import pyromat as pm

pm.config['unit_pressure'] = 'MPa'
F = pm.get('mp.H2O')

F.d_s(T=500, s=5.5)
# Raises UnboundLocalError: local variable 'x' referenced before assignment
```

Bugfix Pull Request incoming

**Comment by chmarti1** [comment]
This issue was due to a bug in d_s.  Just like jranalli says, the density bounds on the iteration were not properly initialized in some cases, and this was not caught in testing.  There was also an issue that the function to crash with some kinds of arrays.  Both of these issues are addressed with release 2.1.5.
