### ISSUE TITLE
Another bracketing issue

### ISSUE THREAD

**Issue by jranalli** [chmarti1/PYroMat#22]
Getting some bracketing errors in the supercritical region. Here's some sample code:

```
import pyromat as pm

pm.config['unit_pressure'] = 'MPa'

water = pm.get('mp.H2O')
#  d works
d = water.d(p=25, T = 650)  # yield 488.840
#  p works
d = water.p(T=650, d=488.840)  # yield 24.999...
# T fails
T = water.T(p=25, d=488.840)  # raise PMParamError
```

**Comment by chmarti1** [comment]
Confirmed.  I can recreate the fault in multiple unit systems, so it is not a unit conversion issue.  The fault is also reproduceable with minor tweaks to the values.

The _T() algorithm has been stable for years, so it is possible that some of the improvements to the newer iteration algorithms were never ported to _T().
________________________________
From: Joe Ranalli ***@***.***>
Sent: Friday, September 24, 2021 1:24 PM
To: chmarti1/PYroMat ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chmarti1/PYroMat] Another bracketing issue (#22)


Getting some bracketing errors in the supercritical region. Here's some sample code:

import pyromat as pm

pm.config['unit_pressure'] = 'MPa'

water = pm.get('mp.H2O')
#  d works
d = water.d(p=25, T = 650)  # yield 488.840
#  p works
d = water.p(T=650, d=488.840)  # yield 24.999...
# T fails
T = water.T(p=25, d=488.840)  # raise PMParamError


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchmarti1%2FPYroMat%2Fissues%2F22&data=04%7C01%7Ccrm28%40psu.edu%7C047222671e224ba007a308d97f801fb0%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637681010541630534%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5jAyXKCVxIkmAfZ61eMIUVPh1BYYlQtwaXgoLdVjrmM%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEVXQ4WPM7TSI4VCIVEUIJTUDSX3VANCNFSM5EWMWNRQ&data=04%7C01%7Ccrm28%40psu.edu%7C047222671e224ba007a308d97f801fb0%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637681010541640516%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JcREa28y4HOQmpJuNHRSr%2B0JiFfXkjwVZytFAP2o4z0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccrm28%40psu.edu%7C047222671e224ba007a308d97f801fb0%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637681010541650512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=J03hd56m5nR6bh0q2OccZGiQvef06u8RoyTI3bxEy1E%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccrm28%40psu.edu%7C047222671e224ba007a308d97f801fb0%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637681010541650512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7YdjGKeVugxtBv36UzPfOCU9ozhfr%2FbVtibBuBJuHMY%3D&reserved=0>.

**Comment by chmarti1** [comment]
The cause was a known numerical problem with bracketing during temperature iteration.  The _tditer() helper method was already established to solve this issue in T_h() and T_s(), but by oversight, it was never added to the _T() method.  This was not caught in testing.  Good catch!
